[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "zisi"

[context.production.environment]
  NODE_VERSION = "18"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
